### ISSUE TITLE
Failed to activate the Hydrogen package

### ISSUE THREAD

**Issue by eskemojoe007** [nteract/hydrogen#518]
I am new to the hydrogen package, but it was working excellent.  Then atom updated and I can't seem to get it to activate.

Hydrogen: 1.0.1
Atom: 1.12.6
System: macOS 10.12.1

I have attempted the apm rebuild, the removal of the node_modules folder with a apm install after.  None have worked.  I have pasted the stack trace as well

```
Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/kernel.coffee:7:7)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/kernel.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/ws-kernel.coffee:8:10)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/ws-kernel.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/signal-list-view.coffee:4:12)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/signal-list-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/main.coffee:7:18)
    at Object.<anonymous> (/Users/folkner/.atom/packages/Hydrogen/lib/main.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:741:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:174:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:821:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:240:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59) 
```

**Comment by lgeiger** [comment]
Unfortunately `apm rebuild` doesn't work with Hydrogen at the moment. https://github.com/mafintosh/prebuild/pull/135 should fix it.

I would recommend you try
```
apm uninstall hydrogen
apm install hydrogen
```
to install a from scratch.

**Comment by FriedaKallotter** [comment]
I am having this problem as well. In Atom it states:
Failed to activate the Hydrogen package
Cannot find module '../build/Release/zmq.node'

Before that Hydrogen was working fine. I changed some Packages and was trying to fix an error with PyLs. After a while Hydrogen gave me this error. But I am not exactly sure which exact steps I took to break it.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0


### Stack Trace

Failed to activate the Hydrogen package

```
At Cannot find module '../build/Release/zmq.node'

Error: Cannot find module '../build/Release/zmq.node'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
     -6:44.6.0 hydrogen:run-all (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
autocomplete-python 1.12.0 
busy-signal 2.0.0 
Hydrogen 2.8.0 
ide-python 1.2.1 
intentions 1.1.5 
linter 2.0.0 
linter-pylint 2.1.1 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.9.0 
python-runner 1.2.1 
run-python-simply 0.6.0 
```

**Comment by thomasbazeille** [comment]
> Failed to activate the Hydrogen package
I get the same error message (but not the same trace) after after upgrading it to v2.8.0. To solve this, I downgraded fro now to v2.7.0 through:
```
apm uninstall hydrogen
apm install hydrogen@2.7.0
```
With that, everything works fine in this version in Atom 1.26.1

```
Error (0 , _util.promisify) is not a function

Full Stack Trace:
TypeError: (0 , _util.promisify) is not a function
    at Object.<anonymous> (/Users/thomasbazeille/.atom/packages/Hydrogen/lib/import-notebook.js:15:19)
    at Object.<anonymous> (/Users/thomasbazeille/.atom/packages/Hydrogen/lib/import-notebook.js:148:2)
    at Module.get_Module._compile (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/thomasbazeille/.atom/packages/Hydrogen/lib/main.js:57:47)
    at Object.<anonymous> (/Users/thomasbazeille/.atom/packages/Hydrogen/lib/main.js:588:24)
    at Module.get_Module._compile (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/l_/wjqqm1010t59yh1sn_rqg88h0000gn/T/AppTranslocation/A97BDDAC-E76A-4AEC-8A9A-9A7CECC54625/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
The error was thrown from the Hydrogen package. This issue has already been reported.```

**Comment by kylebarron** [comment]
@thomasbazeille 	you need to update to a newer version of Atom
