### ISSUE TITLE
Hydrogen 2.8.0 requires Atom >= 1.28.0, error thrown on earlier versions

### ISSUE THREAD

**Issue by nils-werner** [nteract/hydrogen#1551]
This is an issue affecting everyone using an older version of Atom, i.e. [Ubuntu using the webupd8team PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/atom):

Hydrogen 2.8.0 ships with code that requires Node 8, and thus only works with Atom 1.28 or newer (Electron 2.0 was introduced then, which in turn ships with Node 8.x). Installing Hydrogen on an older version of Atom will work, but running any code will fail.

### Steps to reproduce

1. Install Atom < 1.28
2. Install latest Hydrogen version
3. Run any code

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04.2
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Temporary Fix

Install an earlier version of Hydrogen using `apm`

```
apm install Hydrogen@2.7.0
```

### Stack Trace

Failed to activate the Hydrogen package

```
At (0 , _util.promisify) is not a function

TypeError: (0 , _util.promisify) is not a function
    at /packages/Hydrogen/lib/import-notebook.js:15:19)
    at /packages/Hydrogen/lib/import-notebook.js:148:2)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/lib/main.js:57:47)
    at /packages/Hydrogen/lib/main.js:588:24)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/opt/atom/resources/app/src/package.js:782:33)
    at Package.activateNow (/opt/atom/resources/app/src/package.js:220:40)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (/opt/atom/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:02.5.0 hydrogen:run-and-move-down (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.8.0 
```

### Permanent Fix

Right now, `package.json` states

```
"engines": {
  "atom": ">=1.20.0 <2.0.0"
},
```

which should probably be changed to

```
"engines": {
  "atom": ">=1.28.0 <2.0.0"
},
```

Ideally, Hydrogen 2.8.0 should retroactively be changed to fix this, so that `apm` can pick up the correct version automatically.

**Comment by joseppinilla** [comment]
I was having issues with Hydrogen 2.8.0 and Atom>1.28.0.
I solved this by updating ipykernel
`pip install --upgrade ipykernel`

**Comment by kylebarron** [comment]
Is there a way to use `promisify` in Node 6? @BenRussert

**Comment by BenRussert** [comment]
We could just use callbacks.

**Comment by kylebarron** [comment]
Atom 1.28.0 was released June 21, 2018. That's probably recent enough to try to support it? I'm guessing the vast majority of users would use the most recent version.

@nils-werner 	Is there a reason you're using that PPA? The description of that PPA says

> Please use the official repository instead: https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux

**Comment by nils-werner** [comment]
@kylebarron interesting, I didn't know of that PPA

**Comment by kylebarron** [comment]
Does this solve your issue? If so we might bump the Atom version requirement to >= 1.28.0
