### ISSUE TITLE
Installation doesn't work on ubuntu 18.04

### ISSUE THREAD

**Issue by aureliendejode** [nteract/hydrogen#1776]
### Prerequisites

* [ checked] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ checked] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

[Impossible to install hydrogen]

### Steps to Reproduce

1. [Open terminal window]
2. [apm install hydrogen]
3. [and so on...]

### Versions

OS version:
[Your OS's version]

> `atom --version`

```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.15+
git 2.17.1

```

Hydrogen version:

[Your Hydrogen's version]

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ no] hydrogen-python
- [ no] Hydrogen Launcher
- [ no] Data Explorer

### Logs

[Installing hydrogen to /home/aurelien/.atom/packages ✗

> zeromq@5.1.0 install /tmp/apm-install-dir-119818-11409-fdj9xt.jvna/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-119818-11409-fdj9xt.jvna/node_modules/Hydrogen/node_modules/zeromq/scripts/prebuild-install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-119818-11409-fdj9xt.jvna/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119818-11409-fdj9xt.jvna/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-119818-11409-fdj9xt.jvna No description
npm WARN apm-install-dir-119818-11409-fdj9xt.jvna No repository field.
npm WARN apm-install-dir-119818-11409-fdj9xt.jvna No README data
npm WARN apm-install-dir-119818-11409-fdj9xt.jvna No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aurelien/.atom/.apm/_logs/2019-09-18T13_46_54_998Z-debug.log

]

### Expected behavior

[Completed installation.]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
I would look into what could be wrong with your installation, if it is correct, I would view this issue, #1613. You may also be able to search the atom forms or post in the atom slack, but I don't believe we can give you a good answer as to what caused this. However its definitely not caused by us but rather how you are installing.

**Comment by wadethestealth** [comment]
I believe this is an apm error like #1762, and am closing for the same reason, but also because there has been no update.

**Comment by wadethestealth** [comment]
Future readers can visit #1844 for a related issue that is more accurate than this thread.
